# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'MyBaseOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyBaseOC
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SVProgressHUD'

end
